fix #54
freifunk-berlin/ca.berlin.freifunk.net pull request #58
Opened 2017-12-19 16:07 UTC by niccokunzmann

fix #54

Satz wird eingefügt.

2017-12-19 18:25 UTC, SvenRoederer commented
@niccokunzmann kannst du die Commit-message etwas aussagekräftiger machen?
Dann man nicht erst bei Github nachsehen muss, was mit "#54" gemeint ist.

2017-12-20 14:50 UTC, niccokunzmann commented
@SvenRoederer ich habe den Titel eingefügt

2018-01-11 20:19 UTC, SvenRoederer requested changes

2018-01-11 20:19 UTC, SvenRoederer commented on ca/templates/_layout.html
> +    ca.berlin.freifunk.net wird von der Berliner Freifunk-Gemeinschaft <a href="https://github.com/freifunk-berlin/ca.berlin.freifunk.net">auf GitHub</a> entwickelt. Du kannst mithelfen und die Softw
to hard-code "ca.berlin.freifunk.net" ist eher unpraktisch. Denn der Code wird auch bei "tunnel.berlin.freifunk.net" genutzt.

P.S: ich dachte, ich schrieb das schon mal ....

2018-03-20 20:20 UTC, SvenRoederer commented on ca/templates/_layout.html
> +    ca.berlin.freifunk.net wird von der Berliner Freifunk-Gemeinschaft <a href="https://github.com/freifunk-berlin/ca.berlin.freifunk.net">auf GitHub</a> entwickelt. Du kannst mithelfen und die Softw
Vorschlag: " ca.berlin.freifunk.net" ändern in "dieser Web-service"

2018-03-20 22:19 UTC, niccokunzmann commented
@SvenRoederer Ich habe es in 8bb5b5f addressiert.

2018-05-14 23:45 UTC, bobster-galore commented
Would be nice! How to progress?

2018-05-15 19:07 UTC, SvenRoederer commented
jetzt wo ich den Kommentar von @niccokunzmann wieder sehe, fällt mir wieder ein, was hier Schuld war: die Arbeit an Hedy 1.0.0 ....

2018-05-15 19:10 UTC, merged

2018-05-15 19:23 UTC, niccokunzmann commented
Danke!